### ISSUE TITLE
Button feedback

### ISSUE THREAD

**Issue by otajor** [daUnicorns/daunicorns.github.io#24]
The app works well, but it would be better if the user could tell when the button had been clicked. Nothing on the page visibly changes - the button always just looks like this:

<img width="228" alt="screen shot 2016-02-05 at 10 54 25" src="https://cloud.githubusercontent.com/assets/13705650/12844397/f9b1b00e-cbf6-11e5-875f-0b01424f275a.png">

You could add hover or onclick effects in CSS like this:

``` css
submitBtn:hover {
     background-color: blue;
}
```

or 

``` css
/* for onclick effect */
submitBtn:active {
     background-color: blue;
}
```
